name: Compile/Test on Windows and Mac

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [macos-vulkan, windows-vulkan]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-vulkan
            c_compiler: cl
            cpp_compiler: cl
          - os: macos-vulkan
            c_compiler: clang
            cpp_compiler: clang++
          - os: macos-vulkan
            c_compiler: gcc
            cpp_compiler: g++
        exclude:
          - os: windows-vulkan
            c_compiler: gcc
          - os: windows-vulkan
            c_compiler: clang
          - os: macos-vulkan
            c_compiler: cl

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: >
        cmake -B ${{ github.workspace }}/build
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --parallel

    #- name: Test
    #  working-directory: ${{ steps.strings.outputs.build-output-dir }}
      # Execute tests defined by the CMake configuration. Note that --build-config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
    #  run: ctest --build-config ${{ matrix.build_type }}